opt_in_rules:
- empty_count
- empty_string
- force_unwrapping
- unused_optional_binding
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 100
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
cyclomatic_complexity:
    warning: 15
    error: 25
identifier_name:
    allowed_symbols: ["_"]
    validates_start_with_lowercase: false
    min_length:
        warning: 3
        error: 1
    
reporter: "xcode"
